// Generated by gencpp from file beginner_tutorial/DoDishesFeedback.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIAL_MESSAGE_DODISHESFEEDBACK_H
#define BEGINNER_TUTORIAL_MESSAGE_DODISHESFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorial
{
template <class ContainerAllocator>
struct DoDishesFeedback_
{
  typedef DoDishesFeedback_<ContainerAllocator> Type;

  DoDishesFeedback_()
    : percentage_completed(0.0)  {
    }
  DoDishesFeedback_(const ContainerAllocator& _alloc)
    : percentage_completed(0.0)  {
  (void)_alloc;
    }



   typedef float _percentage_completed_type;
  _percentage_completed_type percentage_completed;





  typedef boost::shared_ptr< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DoDishesFeedback_

typedef ::beginner_tutorial::DoDishesFeedback_<std::allocator<void> > DoDishesFeedback;

typedef boost::shared_ptr< ::beginner_tutorial::DoDishesFeedback > DoDishesFeedbackPtr;
typedef boost::shared_ptr< ::beginner_tutorial::DoDishesFeedback const> DoDishesFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorial': ['/home/george/rain_ws/src/beginner_tutorial/msg', '/home/george/rain_ws/devel/share/beginner_tutorial/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26e2c7154b190781742892deccb6c8f0";
  }

  static const char* value(const ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26e2c7154b190781ULL;
  static const uint64_t static_value2 = 0x742892deccb6c8f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorial/DoDishesFeedback";
  }

  static const char* value(const ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"#Define the feedback message\n"
"\n"
"float32 percentage_completed\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage_completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoDishesFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorial::DoDishesFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage_completed: ";
    Printer<float>::stream(s, indent + "  ", v.percentage_completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIAL_MESSAGE_DODISHESFEEDBACK_H
