// Generated by gencpp from file beginner_tutorial/SetLedRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIAL_MESSAGE_SETLEDREQUEST_H
#define BEGINNER_TUTORIAL_MESSAGE_SETLEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorial
{
template <class ContainerAllocator>
struct SetLedRequest_
{
  typedef SetLedRequest_<ContainerAllocator> Type;

  SetLedRequest_()
    : ledNumber(0)  {
    }
  SetLedRequest_(const ContainerAllocator& _alloc)
    : ledNumber(0)  {
  (void)_alloc;
    }



   typedef int64_t _ledNumber_type;
  _ledNumber_type ledNumber;





  typedef boost::shared_ptr< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLedRequest_

typedef ::beginner_tutorial::SetLedRequest_<std::allocator<void> > SetLedRequest;

typedef boost::shared_ptr< ::beginner_tutorial::SetLedRequest > SetLedRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorial::SetLedRequest const> SetLedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorial::SetLedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorial': ['/home/george/rain_ws/src/beginner_tutorial/msg', '/home/george/rain_ws/devel/share/beginner_tutorial/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66b814d8f799f055d2077b8720d602a4";
  }

  static const char* value(const ::beginner_tutorial::SetLedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66b814d8f799f055ULL;
  static const uint64_t static_value2 = 0xd2077b8720d602a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorial/SetLedRequest";
  }

  static const char* value(const ::beginner_tutorial::SetLedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ledNumber\n"
;
  }

  static const char* value(const ::beginner_tutorial::SetLedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ledNumber);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorial::SetLedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorial::SetLedRequest_<ContainerAllocator>& v)
  {
    s << indent << "ledNumber: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ledNumber);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIAL_MESSAGE_SETLEDREQUEST_H
