// Generated by gencpp from file beginner_tutorial/SetLedResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIAL_MESSAGE_SETLEDRESPONSE_H
#define BEGINNER_TUTORIAL_MESSAGE_SETLEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorial
{
template <class ContainerAllocator>
struct SetLedResponse_
{
  typedef SetLedResponse_<ContainerAllocator> Type;

  SetLedResponse_()
    : led_colour()
    , sucess(false)  {
    }
  SetLedResponse_(const ContainerAllocator& _alloc)
    : led_colour(_alloc)
    , sucess(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _led_colour_type;
  _led_colour_type led_colour;

   typedef uint8_t _sucess_type;
  _sucess_type sucess;





  typedef boost::shared_ptr< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetLedResponse_

typedef ::beginner_tutorial::SetLedResponse_<std::allocator<void> > SetLedResponse;

typedef boost::shared_ptr< ::beginner_tutorial::SetLedResponse > SetLedResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorial::SetLedResponse const> SetLedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorial::SetLedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorial': ['/home/george/rain_ws/src/beginner_tutorial/msg', '/home/george/rain_ws/devel/share/beginner_tutorial/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85267a6bbc2dfc9a9b19c94073f906c7";
  }

  static const char* value(const ::beginner_tutorial::SetLedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85267a6bbc2dfc9aULL;
  static const uint64_t static_value2 = 0x9b19c94073f906c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorial/SetLedResponse";
  }

  static const char* value(const ::beginner_tutorial::SetLedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string led_colour\n"
"bool sucess\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorial::SetLedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_colour);
      stream.next(m.sucess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorial::SetLedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorial::SetLedResponse_<ContainerAllocator>& v)
  {
    s << indent << "led_colour: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.led_colour);
    s << indent << "sucess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sucess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIAL_MESSAGE_SETLEDRESPONSE_H
