// Generated by gencpp from file beginner_tutorial/SetLed.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIAL_MESSAGE_SETLED_H
#define BEGINNER_TUTORIAL_MESSAGE_SETLED_H

#include <ros/service_traits.h>


#include <beginner_tutorial/SetLedRequest.h>
#include <beginner_tutorial/SetLedResponse.h>


namespace beginner_tutorial
{

struct SetLed
{

typedef SetLedRequest Request;
typedef SetLedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLed
} // namespace beginner_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorial::SetLed > {
  static const char* value()
  {
    return "4f6f9e0f1aea45167fb7e47754ca5768";
  }

  static const char* value(const ::beginner_tutorial::SetLed&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorial::SetLed > {
  static const char* value()
  {
    return "beginner_tutorial/SetLed";
  }

  static const char* value(const ::beginner_tutorial::SetLed&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorial::SetLedRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorial::SetLed > 
template<>
struct MD5Sum< ::beginner_tutorial::SetLedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorial::SetLed >::value();
  }
  static const char* value(const ::beginner_tutorial::SetLedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorial::SetLedRequest> should match 
// service_traits::DataType< ::beginner_tutorial::SetLed > 
template<>
struct DataType< ::beginner_tutorial::SetLedRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorial::SetLed >::value();
  }
  static const char* value(const ::beginner_tutorial::SetLedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorial::SetLedResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorial::SetLed > 
template<>
struct MD5Sum< ::beginner_tutorial::SetLedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorial::SetLed >::value();
  }
  static const char* value(const ::beginner_tutorial::SetLedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorial::SetLedResponse> should match 
// service_traits::DataType< ::beginner_tutorial::SetLed > 
template<>
struct DataType< ::beginner_tutorial::SetLedResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorial::SetLed >::value();
  }
  static const char* value(const ::beginner_tutorial::SetLedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIAL_MESSAGE_SETLED_H
