(cl:defpackage beginner_tutorial-msg
  (:use )
  (:export
   "<DODISHESACTION>"
   "DODISHESACTION"
   "<DODISHESACTIONFEEDBACK>"
   "DODISHESACTIONFEEDBACK"
   "<DODISHESACTIONGOAL>"
   "DODISHESACTIONGOAL"
   "<DODISHESACTIONRESULT>"
   "DODISHESACTIONRESULT"
   "<DODISHESFEEDBACK>"
   "DODISHESFEEDBACK"
   "<DODISHESGOAL>"
   "DODISHESGOAL"
   "<DODISHESRESULT>"
   "DODISHESRESULT"
   "<NUM>"
   "NUM"
  ))

